/**
 * Worker entry that wraps the OpenNext-generated worker to add a `scheduled`
 * handler: Cloudflare cron triggers do not hit HTTP routes, so the tick is
 * translated into an in-process POST to /api/pro/capture (see
 * src/app/api/pro/capture/route.ts). Normal traffic passes through unchanged.
 */

// Deliberately ts-ignore, not ts-expect-error: the import only fails to
// resolve before `opennextjs-cloudflare build` has run, so an expect-error
// would itself error ("unused directive") after a build.
// biome-ignore lint/suspicious/noTsIgnore: see above
// @ts-ignore -- generated by `opennextjs-cloudflare build`, absent before it
import handler from "./.open-next/worker.js";

interface Env {
  CRON_SECRET?: string;
}

interface Ctx {
  waitUntil(promise: Promise<unknown>): void;
}

export default {
  fetch: handler.fetch,

  async scheduled(_controller: unknown, env: Env, ctx: Ctx) {
    const response: Response = await handler.fetch(
      new Request("https://festicycling.com/api/pro/capture", {
        method: "POST",
        headers: { authorization: `Bearer ${env.CRON_SECRET}` },
      }),
      env,
      ctx,
    );
    if (!response.ok) {
      console.error(
        `Telemetry capture failed: ${response.status} ${await response.text()}`,
      );
    }
  },
};

// Wrangler resolves Durable Object classes via the `main` entry, so the ones
// the OpenNext worker exports must be re-exported here. None are bound today
// (defineCloudflareConfig() without options), but enabling e.g. the DO queue
// or sharded tag cache later would silently break without this.
// biome-ignore format: single line so the ts-ignore covers the specifier
// biome-ignore lint/suspicious/noTsIgnore: see the import above
// @ts-ignore -- generated by `opennextjs-cloudflare build`, absent before it
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
