/** Every kind of notification we can send. Keep in sync with the Prisma `NotificationType` enum. */
export const NotificationType = {
  USER_FOLLOWED: "USER_FOLLOWED",
  GROUP_JOINED: "GROUP_JOINED",
  GROUP_JOIN_REQUESTED: "GROUP_JOIN_REQUESTED",
  GROUP_JOIN_APPROVED: "GROUP_JOIN_APPROVED",
  GROUP_JOIN_REJECTED: "GROUP_JOIN_REJECTED",
  GROUP_RIDE_CREATED: "GROUP_RIDE_CREATED",
  RIDE_JOIN_REQUEST: "RIDE_JOIN_REQUEST",
  RIDE_JOIN_APPROVED: "RIDE_JOIN_APPROVED",
  RIDE_JOIN_REJECTED: "RIDE_JOIN_REJECTED",
  RIDE_UPDATED: "RIDE_UPDATED",
  RIDE_CANCELLED: "RIDE_CANCELLED",
  RIDE_WAITLIST_PROMOTED: "RIDE_WAITLIST_PROMOTED",
  POST_LIKED: "POST_LIKED",
  POST_COMMENTED: "POST_COMMENTED",
} as const;

export type NotificationType =
  (typeof NotificationType)[keyof typeof NotificationType];
